### ISSUE TITLE
Proper installation but not pyton

### ISSUE THREAD

**Issue by hugosoli** [MTG/homebrew-essentia#15]
I just followed the instructions on how to install essentia on MAC with homebrew. It seems properly installed but I tried to used
import essentia
on python and the module is not founded.
Wondering if I need to do another step.
Cheers

**Comment by dbogdanov** [comment]
What's your ```which python``` output? You shouldn't use the system Python, but the one installed by the Homebrew formula as a dependency (when installing Essentia via Homebrew, the formula also installs Python). 

For example, on my machine: 

```
dbogdanov@poblenou-135-52:~$ which python
/usr/local/opt/python/libexec/bin/python
```
which is actually a symlink to the system's Python:
```
dbogdanov@poblenou-135-52:~$ ls -l /usr/local/opt/python/libexec/bin/python
lrwxr-xr-x  1 dbogdanov  staff  60  8 jul 20:31 /usr/local/opt/python/libexec/bin/python -> ../../Frameworks/Python.framework/Versions/3.7/bin/python3.7
```

```
dbogdanov@poblenou-135-52:~$ which python3
/usr/local/bin/python3
```
is a symlink to Python 3 installed by Homebrew
```
dbogdanov@poblenou-135-52:~$ ls -lh /usr/local/bin/python3
lrwxr-xr-x  1 dbogdanov  admin    34B 29 jul 17:41 /usr/local/bin/python3 -> ../Cellar/python/3.7.4/bin/python3
```

**Comment by hugosoli** [comment]
Thanks Dimitry, that was the issue.
Warm regards
