### ISSUE TITLE
Not sure what is the failure 

### ISSUE THREAD

**Issue by Bill200516** [MTG/homebrew-essentia#24]
Hi,

First of all, thank you so much for making this feature available.

I seriously have trouble understanding what are the causes that fail that installation on my laptop. 

My apology, but I hope you could give me a hand if possible; the following info is what I can think of, hopefully its sufficient to help you reason out the potential issues. : 

1.  Attempted to install on: MacOS Catalina Version 10.15.5.
2. Using Python : 3.7.4 ; Conda Version : 4.9.2;
3. The last few outputs are:

→ Building only Essentia's python bindings (libessentia should be pre-installed)
Checking for program 'pkg-config'        : /usr/local/Homebrew/Library/Homebrew/shims/mac/super/pkg-config 
Checking for 'essentia'                  : yes 
Checking for 'clang' (C compiler)        : clang 
Checking for program 'python'            : /usr/local/opt/python@3.8/bin/python3.8 
Checking for python version >= 2.7.0     : 3.8.6 
→ Configuring for python3
python-config                            : /usr/local/opt/python@3.8/bin/python3.8-config 
Asking python-config for pyext '--cflags --libs --ldflags' flags : yes 
Testing pyext configuration                                      : yes 
Checking for python module 'numpy'                               : not found 
Could not find the python module 'numpy'
(complete log in /private/tmp/essentia-20201117-69375-15bs9yb/build/config.log)

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/mtg/homebrew-essentia/issues

These open issues may also help:
essentia installs fine, but gaia fails https://github.com/MTG/homebrew-essentia/issues/22
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels.

----- END -----

Regardless, thank you for time and effort in advance.

Cheers,
Bill

**Comment by PRamoneda** [comment]
Brew formula is not working for me too.

**Comment by bps10** [comment]
I was seeing the same error. From your logs (and mine), it looks like the formula is failing because it is using python 3.8.6, not 3.7 as you believed:
```
python-config : /usr/local/opt/python@3.8/bin/python3.8-config
```
which does not have numpy installed:
```
Checking for python module 'numpy' : not found
```

I fixed this by installing numpy into that python version with:
```
/usr/local/opt/python@3.8/bin/pip3.8 install numpy
```

Now I can import essentia from the python installed at `/usr/local/opt/python@3.8/bin/python3.8`.

This is not an ideal solution. There must be a way to either specify the python version homebrew should use or at least add numpy as a requirement to the formula, but unfortunately I don't know enough about homebrew/ruby to suggest a change.

**Comment by Bill200516** [comment]
Hi @PRamoneda @bps10 , feel free to share your solutions if you guys managed to overcome the issue. Thank you.

**Comment by PRamoneda** [comment]
@Bill200516 I am using the docker image: https://github.com/MTG/essentia-docker.

**Comment by dantrueman** [comment]
@Bill200516 Did you ever find a Mac solution? similar issue here, thanks...

**Comment by kplai2020** [comment]
Hi @dantrueman , I asked PRamoneda (above your comment), you may want to follow the link provided by him: https://github.com/MTG/essentia-docker . Hope this helps.

**Comment by dbogdanov** [comment]
Brew installation of Essentia relies on using the Python installed by brew (currently, `python@3.9`). We do have [a dependency on numpy](https://github.com/MTG/homebrew-essentia/blob/master/essentia.rb#L23), so it should have been installed automatically. 

Feel free to open a new issue in the case you find any further problems.
