### ISSUE TITLE
Installation failed on macOS Big Sur

### ISSUE THREAD

**Issue by Amzyshk** [MTG/homebrew-essentia#25]
`brew install essentia --HEAD` fails on latest macOS Big Sur.

The error message is: 
`Error: libbluray: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead.`

I am using macOS Big Sur, v 11.1.

**Comment by AnurupGuha** [comment]
Have the same issue.

**Comment by dbogdanov** [comment]
Try updating brew. The [newest version of libbluray](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libbluray.rb) doesn't have dependency on java. (Fixed in https://github.com/Homebrew/homebrew-core/pull/68068).
