### ISSUE TITLE
Add -no-msse flag for Apple Silicon

### ISSUE THREAD

**Issue by jaburgoyne** [MTG/homebrew-essentia#27]
The current formula *almost* installs fine on Apple Silicon, but the -no-msse flag is necessary for WAF, both in build_flags and in python_flags.

I’m not experienced enough with writing Homebrew formulae to know how add a flag conditional on the architecture, but as a workaround in the meantime, Essentia will build just fine on an M1 Mac if you add this flag manually in those two places.

**Comment by dbogdanov** [comment]
Should be resolved with https://github.com/MTG/essentia/commit/8e5652c8fad054843b844e08037866ae5828a9ee.
