### ISSUE TITLE
task in 'essentia' failed with exit status 1

### ISSUE THREAD

**Issue by pkrickeb** [MTG/homebrew-essentia#28]
2021-08-18 23:45:07 +0200

/opt/homebrew/opt/python@3.9/bin/python3
waf

Waf: Entering directory `/private/tmp/essentia-20210818-51986-p0fki4/build'
→ building from /private/tmp/essentia-20210818-51986-p0fki4
→ building from /private/tmp/essentia-20210818-51986-p0fki4/src
Building all the algorithms
Ignoring the following algorithms: TensorflowPredict, TensorflowPredictMusiCNN, FFTK, TensorflowPredictVGGish, MusicExtractorSVM, IFFTK, FFTAComplex, FFTKComplex, TensorflowPredictTempoCNN, GaiaTransform, IFFTKComplex, TempoCNN, IFFTAComplex, IFFTA, FFTA
Created algorithms registration file
→ building from /private/tmp/essentia-20210818-51986-p0fki4/src/examples
[  1/301] Compiling src/algorithms/rhythm/tempotapmaxagreement.cpp
[  2/301] Compiling src/algorithms/extractor/barkextractor.cpp
[  3/301] Compiling src/algorithms/tonal/chordsdescriptors.cpp
[  4/301] Compiling src/essentia/utils/extractor_music/MusicLowlevelDescriptors.cpp
[  5/301] Compiling src/essentia/streaming/algorithms/ringbufferinput.cpp
[  6/301] Compiling src/essentia/parameter.cpp
[  7/301] Compiling src/essentia/connector.cpp
[  8/301] Compiling src/essentia/algorithm.cpp
error: unknown FP unit 'sse'

error: unknown FP unit 'sse'

error: unknown FP unit 'sse'

error: unknown FP unit 'sse'

error: unknown FP unit 'sse'

error: unknown FP unit 'sse'

error: unknown FP unit 'sse'

error: unknown FP unit 'sse'

Waf: Leaving directory `/private/tmp/essentia-20210818-51986-p0fki4/build'
Build failed
 -> task in 'essentia' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia' failed with exit status 1 (run with -v to display more information)
 -> task in 'essentia' failed with exit status 1 (run with -v to display more information)

HOMEBREW_VERSION: 3.2.8
ORIGIN: https://github.com/Homebrew/brew
HEAD: f026dd21c195952747395ebdda24327204f012ec
Last commit: 24 hours ago 
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 1f30689d7e32f491f20170bf28604f1ed38fe95b
Core tap last commit: 33 minutes ago 
Core tap branch: master
HOMEBREW_PREFIX: /opt/homebrew
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_BOOTSNAP: set
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit arm_firestorm_icestorm
Clang: 12.0.5 build 1205
Git: 2.30.1 => /Library/Developer/CommandLineTools/usr/bin/git
Curl: 7.64.1 => /usr/bin/curl
macOS: 11.5-arm64
CLT: 12.5.1.0.1.1623191612
Xcode: N/A
Rosetta 2: false

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /opt/homebrew/opt/openssl@1.1:/opt/homebrew/opt/libffi:/opt/homebrew/opt/m4:/opt/homebrew/opt/readline:/opt/homebrew/opt/sqlite:/opt/homebrew/opt/icu4c:/opt/homebrew/opt/openblas:/opt/homebrew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /opt/homebrew/opt/python@3.9/Frameworks
PKG_CONFIG_PATH: /opt/homebrew/opt/libyaml/lib/pkgconfig:/opt/homebrew/opt/gmp/lib/pkgconfig:/opt/homebrew/opt/isl/lib/pkgconfig:/opt/homebrew/opt/mpfr/lib/pkgconfig:/opt/homebrew/opt/zstd/lib/pkgconfig:/opt/homebrew/opt/hwloc/lib/pkgconfig:/opt/homebrew/opt/openssl@1.1/lib/pkgconfig:/opt/homebrew/opt/libevent/lib/pkgconfig:/opt/homebrew/opt/open-mpi/lib/pkgconfig:/opt/homebrew/opt/fftw/lib/pkgconfig:/opt/homebrew/opt/aom/lib/pkgconfig:/opt/homebrew/opt/dav1d/lib/pkgconfig:/opt/homebrew/opt/libpng/lib/pkgconfig:/opt/homebrew/opt/freetype/lib/pkgconfig:/opt/homebrew/opt/fontconfig/lib/pkgconfig:/opt/homebrew/opt/frei0r/lib/pkgconfig:/opt/homebrew/opt/bdw-gc/lib/pkgconfig:/opt/homebrew/opt/libffi/lib/pkgconfig:/opt/homebrew/opt/readline/lib/pkgconfig:/opt/homebrew/opt/guile/lib/pkgconfig:/opt/homebrew/opt/libidn2/lib/pkgconfig:/opt/homebrew/opt/libtasn1/lib/pkgconfig:/opt/homebrew/opt/nettle/lib/pkgconfig:/opt/homebrew/opt/p11-kit/lib/pkgconfig:/opt/homebrew/opt/c-ares/lib/pkgconfig:/opt/homebrew/opt/jemalloc/lib/pkgconfig:/opt/homebrew/opt/nghttp2/lib/pkgconfig:/opt/homebrew/opt/unbound/lib/pkgconfig:/opt/homebrew/opt/gnutls/lib/pkgconfig:/opt/homebrew/opt/fribidi/lib/pkgconfig:/opt/homebrew/opt/pcre/lib/pkgconfig:/opt/homebrew/opt/sqlite/lib/pkgconfig:/opt/homebrew/opt/xz/lib/pkgconfig:/opt/homebrew/opt/python@3.9/lib/pkgconfig:/opt/homebrew/opt/glib/lib/pkgconfig:/opt/homebrew/opt/libpthread-stubs/lib/pkgconfig:/opt/homebrew/opt/libxau/lib/pkgconfig:/opt/homebrew/opt/libxdmcp/lib/pkgconfig:/opt/homebrew/opt/libxcb/lib/pkgconfig:/opt/homebrew/opt/libx11/lib/pkgconfig:/opt/homebrew/opt/libxext/lib/pkgconfig:/opt/homebrew/opt/libxrender/lib/pkgconfig:/opt/homebrew/opt/lzo/lib/pkgconfig:/opt/homebrew/opt/pixman/lib/pkgconfig:/opt/homebrew/opt/cairo/lib/pkgconfig:/opt/homebrew/opt/gobject-introspection/lib/pkgconfig:/opt/homebrew/opt/graphite2/lib/pkgconfig:/opt/homebrew/opt/icu4c/lib/pkgconfig:/opt/homebrew/opt/harfbuzz/lib/pkgconfig:/opt/homebrew/opt/libass/lib/pkgconfig:/opt/homebrew/opt/libbluray/lib/pkgconfig:/opt/homebrew/opt/libsoxr/lib/pkgconfig:/opt/homebrew/opt/libvidstab/lib/pkgconfig:/opt/homebrew/opt/libogg/lib/pkgconfig:/opt/homebrew/opt/libvorbis/lib/pkgconfig:/opt/homebrew/opt/libvpx/lib/pkgconfig:/opt/homebrew/opt/opencore-amr/lib/pkgconfig:/opt/homebrew/opt/jpeg/lib/pkgconfig:/opt/homebrew/opt/libtiff/lib/pkgconfig:/opt/homebrew/opt/little-cms2/lib/pkgconfig:/opt/homebrew/opt/openjpeg/lib/pkgconfig:/opt/homebrew/opt/opus/lib/pkgconfig:/opt/homebrew/opt/rav1e/lib/pkgconfig:/opt/homebrew/opt/flac/lib/pkgconfig:/opt/homebrew/opt/libsndfile/lib/pkgconfig:/opt/homebrew/opt/libsamplerate/lib/pkgconfig:/opt/homebrew/opt/rubberband/lib/pkgconfig:/opt/homebrew/opt/sdl2/lib/pkgconfig:/opt/homebrew/opt/speex/lib/pkgconfig:/opt/homebrew/opt/srt/lib/pkgconfig:/opt/homebrew/opt/webp/lib/pkgconfig:/opt/homebrew/opt/leptonica/lib/pkgconfig:/opt/homebrew/opt/tesseract/lib/pkgconfig:/opt/homebrew/opt/theora/lib/pkgconfig:/opt/homebrew/opt/x264/lib/pkgconfig:/opt/homebrew/opt/x265/lib/pkgconfig:/opt/homebrew/opt/libsodium/lib/pkgconfig:/opt/homebrew/opt/zeromq/lib/pkgconfig:/opt/homebrew/opt/zimg/lib/pkgconfig:/opt/homebrew/opt/ffmpeg/lib/pkgconfig:/opt/homebrew/opt/taglib/lib/pkgconfig:/opt/homebrew/opt/chromaprint/lib/pkgconfig:/opt/homebrew/opt/openblas/lib/pkgconfig:/opt/homebrew/opt/eigen/share/pkgconfig:/opt/homebrew/opt/xorgproto/share/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/opt/homebrew/Library/Homebrew/os/mac/pkgconfig/11
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk
ACLOCAL_PATH: /opt/homebrew/share/aclocal
PATH: /opt/homebrew/Library/Homebrew/shims/mac/super:/opt/homebrew/opt/pkg-config/bin:/opt/homebrew/opt/gcc/bin:/opt/homebrew/opt/zstd/bin:/opt/homebrew/opt/hwloc/bin:/opt/homebrew/opt/openssl@1.1/bin:/opt/homebrew/opt/libevent/bin:/opt/homebrew/opt/open-mpi/bin:/opt/homebrew/opt/fftw/bin:/opt/homebrew/opt/aom/bin:/opt/homebrew/opt/dav1d/bin:/opt/homebrew/opt/libpng/bin:/opt/homebrew/opt/freetype/bin:/opt/homebrew/opt/fontconfig/bin:/opt/homebrew/opt/m4/bin:/opt/homebrew/opt/libtool/bin:/opt/homebrew/opt/guile/bin:/opt/homebrew/opt/gettext/bin:/opt/homebrew/opt/libidn2/bin:/opt/homebrew/opt/libtasn1/bin:/opt/homebrew/opt/nettle/bin:/opt/homebrew/opt/p11-kit/bin:/opt/homebrew/opt/c-ares/bin:/opt/homebrew/opt/jemalloc/bin:/opt/homebrew/opt/nghttp2/bin:/opt/homebrew/opt/gnutls/bin:/opt/homebrew/opt/lame/bin:/opt/homebrew/opt/fribidi/bin:/opt/homebrew/opt/pcre/bin:/opt/homebrew/opt/gdbm/bin:/opt/homebrew/opt/sqlite/bin:/opt/homebrew/opt/xz/bin:/opt/homebrew/opt/python@3.9/bin:/opt/homebrew/opt/glib/bin:/opt/homebrew/opt/cairo/bin:/opt/homebrew/opt/gobject-introspection/bin:/opt/homebrew/opt/graphite2/bin:/opt/homebrew/opt/icu4c/bin:/opt/homebrew/opt/harfbuzz/bin:/opt/homebrew/opt/libbluray/bin:/opt/homebrew/opt/jpeg/bin:/opt/homebrew/opt/libtiff/bin:/opt/homebrew/opt/little-cms2/bin:/opt/homebrew/opt/openjpeg/bin:/opt/homebrew/opt/rav1e/bin:/opt/homebrew/opt/flac/bin:/opt/homebrew/opt/libsndfile/bin:/opt/homebrew/opt/libsamplerate/bin:/opt/homebrew/opt/rubberband/bin:/opt/homebrew/opt/sdl2/bin:/opt/homebrew/opt/srt/bin:/opt/homebrew/opt/giflib/bin:/opt/homebrew/opt/webp/bin:/opt/homebrew/opt/leptonica/bin:/opt/homebrew/opt/tesseract/bin:/opt/homebrew/opt/x264/bin:/opt/homebrew/opt/x265/bin:/opt/homebrew/opt/zeromq/bin:/opt/homebrew/opt/ffmpeg/bin:/opt/homebrew/opt/taglib/bin:/opt/homebrew/opt/chromaprint/bin:/opt/homebrew/opt/numpy/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by pkrickeb** [comment]
brew install not working.
./waf configure --build-static --no-msse solves the compiling from sources

**Comment by dbogdanov** [comment]
Same issue as #27.
